def idx_convdc():
    """Defines constants for named column indices to converter matrix.

    Returns:
        tuple: (DCDROOP, DCSLACK, DCNOSLACK, PVC, PQC, CONV_BUS, CONVTYPE_DC,
                CONVTYPE_AC, PCONV, QCONV, VCONV, RTF, XTF, BF, RCONV, XCONV,
                BASEKVC, VCMAX, VCMIN, ICMAX, CONVSTATUS, LOSSA, LOSSB, LOSSCR,
                LOSSCI, DROOP, PDCSET, VDCSET, DVDCSET, VMC, VAC, PCCONV, QCCONV,
                PCLOSS, VMF, VAF, PFIL, QCONVF, QCCONVF)

    Example usage:
        DCDROOP, DCSLACK, DCNOSLACK, PVC, PQC, CONV_BUS, CONVTYPE_DC, \
        CONVTYPE_AC, PCONV, QCONV, VCONV, RTF, XTF, BF, RCONV, XCONV, \
        BASEKVC, VCMAX, VCMIN, ICMAX, CONVSTATUS, LOSSA, LOSSB, LOSSCR, \
        LOSSCI, DROOP, PDCSET, VDCSET, DVDCSET, VMC, VAC, PCCONV, QCCONV, \
        PCLOSS, VMF, VAF, PFIL, QCONVF, QCCONVF = idx_convdc()
        Pg = convdc[3, PCONV]          # get the real power output of convertor 4
        convdc[:, CONVTYPE_AC] = PVC   # set all converters in voltage controlling mode

    Column definitions:
     1  CONV_BUS    converter bus number (dc bus numbering)
     2  CONVTYPE_DC dc bus type (1 = constant power, 2 = dc slack, 3 = dc voltage droop)
     3  CONVTYPE_AC ac bus type (1 = PQ, 2 = PV)
     4  PCONV       Ps, active power injected in the ac grid (MW)
     5  QCONV       Qs, reactive power injected in the ac grid (MVAr)
     6  VCONV       Vtar, target voltage of converter connected ac bus (p.u.)
     7  RTF         rtf, transformer resistance (p.u.)
     8  XTF         xtf, transformer reactance (p.u.)
     9  BF          bf, filter susceptance (p.u.)
    10  RCONV       rc, phase reactor resistance (p.u.)
    11  XCONV       xc, phase reactor reactance (p.u.)
    12  BASEKVC     converter baseKV, base voltage (kV)
    13  VCMAX       maxVc, maximum converter voltage magnitude (p.u.)
    14  VCMIN       minVc, minimum converter voltage magnitude (p.u.)
    15  ICMAX       Imax, maximum converter current (p.u.)
    16  CONVSTATUS  converter status (1 = on, 0 = off)
    17  LOSSA       LossA, constant loss coefficient (MW)
    18  LOSSB       LossB, linear loss coefficient(kV)
    19  LOSSCR      LossCrec, rectifier quadratic loss coefficient (Ohm)
    20  LOSSCI      LossCinv, inverter quadratic loss coefficient (Ohm)
    21  DROOP       dc voltage droop (MW/p.u)
    22  PDCSET      voltage droop power set-point (MW)
    23  VDCSET      voltage droop voltage set-point (p.u.)
    24  DVDCSET     voltage droop deadband (p.u.) (optional)
    25  VMC         Vm_C, converter voltage magnitude (p.u.)
    26  VAC         Va_C, converter voltage angle (degrees)
    27  PCCONV      Pc, active power generated by the converter (MW)
    28  QCCONV      Qc, reactive power generated by the converter (MVAr)
    29  PCLOSS      Pl, active converter power losses (MW)
    30  VMF         Vm_F, filter voltage magnitude (p.u.)
    31  VAF         Va_F, filter voltage angle (degrees)
    32  PFIL        Psf or Pcf, active power at filter bus (MW)
    33  QCONVF      Qsf, reactive power through transformer at filter bus (MVAr)
    34  QCCONVF     Qcf, reactive power through reactor at filter bus (MVAr)

    Bus type constants:
     DCDROOP     = 3  dc voltage droop
     DCSLACK     = 2  dc slack bus
     DCNOSLACK   = 1  constant active power bus
     PVC         = 2  constant voltage converter control
     PQC         = 1  constant reactive power converter control

    MatACDC - Copyright (C) 2012 Jef Beerten, KU Leuven
    Converted from MATLAB to Python by Lazar Scekic
    """
    # Bus types
    DCDROOP = 3
    DCSLACK = 2
    DCNOSLACK = 1
    PVC = 2
    PQC = 1

    # Column indices
    CONV_BUS = 0
    CONVTYPE_DC = 1
    CONVTYPE_AC = 2
    PCONV = 3
    QCONV = 4
    VCONV = 5
    RTF = 6
    XTF = 7
    BF = 8
    RCONV = 9
    XCONV = 10
    BASEKVC = 11
    VCMAX = 12
    VCMIN = 13
    ICMAX = 14
    CONVSTATUS = 15
    LOSSA = 16
    LOSSB = 17
    LOSSCR = 18
    LOSSCI = 19
    DROOP = 20
    PDCSET = 21
    VDCSET = 22
    DVDCSET = 23
    VMC = 24
    VAC = 25
    PCCONV = 26
    QCCONV = 27
    PCLOSS = 28
    VMF = 29
    VAF = 30
    PFIL = 31
    QCONVF = 32
    QCCONVF = 33

    return DCDROOP, DCSLACK, DCNOSLACK, PVC, PQC, CONV_BUS, CONVTYPE_DC, \
        CONVTYPE_AC, PCONV, QCONV, VCONV, RTF, XTF, BF, RCONV, XCONV, \
        BASEKVC, VCMAX, VCMIN, ICMAX, CONVSTATUS, LOSSA, LOSSB, LOSSCR, \
        LOSSCI, DROOP, PDCSET, VDCSET, DVDCSET, VMC, VAC, PCCONV, QCCONV, \
        PCLOSS, VMF, VAF, PFIL, QCONVF, QCCONVF


if __name__ == "__main__":
    DCDROOP, DCSLACK, DCNOSLACK, PVC, PQC, CONV_BUS, CONVTYPE_DC, \
        CONVTYPE_AC, PCONV, QCONV, VCONV, RTF, XTF, BF, RCONV, XCONV, \
        BASEKVC, VCMAX, VCMIN, ICMAX, CONVSTATUS, LOSSA, LOSSB, LOSSCR, \
        LOSSCI, DROOP, PDCSET, VDCSET, DVDCSET, VMC, VAC, PCCONV, QCCONV, \
        PCLOSS, VMF, VAF, PFIL, QCONVF, QCCONVF = idx_convdc()

    print("DC Converter Bus Types:")
    print(f"DCDROOP = {DCDROOP}")
    print(f"DCSLACK = {DCSLACK}")
    print(f"DCNOSLACK = {DCNOSLACK}")
    print(f"PVC = {PVC}")
    print(f"PQC = {PQC}")

    print("\nDC Converter Column Indices:")
    print(f"CONV_BUS = {CONV_BUS}")
    print(f"CONVTYPE_DC = {CONVTYPE_DC}")
    print(f"CONVTYPE_AC = {CONVTYPE_AC}")
    print(f"PCONV = {PCONV}")
    print(f"QCONV = {QCONV}")
    print(f"VCONV = {VCONV}")
    print(f"RTF = {RTF}")
    print(f"XTF = {XTF}")
    print(f"BF = {BF}")
    print(f"RCONV = {RCONV}")
    print(f"XCONV = {XCONV}")
    print(f"BASEKVC = {BASEKVC}")
    print(f"VCMAX = {VCMAX}")
    print(f"VCMIN = {VCMIN}")
    print(f"ICMAX = {ICMAX}")
    print(f"CONVSTATUS = {CONVSTATUS}")
    print(f"LOSSA = {LOSSA}")
    print(f"LOSSB = {LOSSB}")
    print(f"LOSSCR = {LOSSCR}")
    print(f"LOSSCI = {LOSSCI}")
    print(f"DROOP = {DROOP}")
    print(f"PDCSET = {PDCSET}")
    print(f"VDCSET = {VDCSET}")
    print(f"DVDCSET = {DVDCSET}")
    print(f"VMC = {VMC}")
    print(f"VAC = {VAC}")
    print(f"PCCONV = {PCCONV}")
    print(f"QCCONV = {QCCONV}")
    print(f"PCLOSS = {PCLOSS}")
    print(f"VMF = {VMF}")
    print(f"VAF = {VAF}")
    print(f"PFIL = {PFIL}")
    print(f"QCONVF = {QCONVF}")
    print(f"QCCONVF = {QCCONVF}")